services:

  rabbitmq:
    image: rabbitmq:3.11.3
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - rabbitmq_net

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: cc_student
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - my_network
  producer:
    build: ./producer    
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER= guest
      - RABBITMQ_PASS=guest
    volumes:
      - ./producer:/app 
    depends_on:
      - rabbitmq  
    networks:
      - my_network
      - rabbitmq_net
         
  consumer_one:
    build: ./consumer_one
    environment:
      #- QUEUE_NAME=health_check
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=cc_student
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=guest
      - RABBITMQ_PASS=guest
    volumes:
      - ./consumer_one:/app
    working_dir: /consumer_one
    depends_on:
      - mysql
      - rabbitmq
    networks:
      - my_network
      - rabbitmq_net

  consumer_two:
    build: ./consumer_two
    environment:
      #- QUEUE_NAME=insert_record
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=cc_student
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=guest
      - RABBITMQ_PASS=guest
    volumes:
      - ./consumer_two:/app
    working_dir: /consumer_two  
    depends_on:
      - mysql
      - rabbitmq
    networks:
      - my_network
      - rabbitmq_net

  consumer_three:
    build: ./consumer_three
    environment:
      # - QUEUE_NAME=delete_record
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=cc_student
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=guest
      - RABBITMQ_PASS=guest
    volumes:
      - ./consumer_three:/consumer_three
    working_dir: /consumer_three
    depends_on:
      - mysql
      - rabbitmq
    networks:
      - my_network
      - rabbitmq_net

  consumer_four:
    build: ./consumer_four
    environment:
      # - QUEUE_NAME=read_database
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=cc_student
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=guest
      - RABBITMQ_PASS=guest
    volumes:
      - ./consumer_four:/app
    working_dir: /consumer_four  
    depends_on:
      - mysql
      - rabbitmq
    networks:
      - my_network
      - rabbitmq_net

networks:
  my_network:
    driver: bridge

  rabbitmq_net:
    driver: bridge
